### ISSUE TITLE
Post deployment `mainnet` infrastructure

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1091]
## Issue
Following the deployment of the `release-mainnet` infrastructure, some maintenance operations need to be done.

## To do
- [x] Add Grafana metrics ingestion with prometheus configuration in infra
- [x] Add Grafana logs ingestion with promtail configuration in infra
- [x] Configure new Grafana instance
- [x] Add Grafana dashboards
- [x] Add Grafana reports
- [x] Destroy stale networks in GCP
- [x] #1085 
- [x] Clean SSH Keys

## Later
- [ ] #986
- [ ] Migrate new DNS zone for `api.mithril.network` in `Mithril` GCP project
- [ ] Optimize VM (CPU, IO, ...)
- [ ] Add PagerDuty or Grafana alerts?
