### ISSUE TITLE
Make `mithril-client` crate a library

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1141]
## Why
In order for third party to harness the capabilities of the Mithril client, we want to open its API and make it also a library.
We also intend to distribute the library on `crates.io`.

## What
Create a `mithril-client` API that allows developers to embed Mithril certificates in their Rust apps.

## How

- [x] Make client API public (API definition/specification, will need a small refactoring, re-exporting of types from `mithril-common`)
  - [x] Expose `SnapshotService` functions: `list`, `show` and `download`
  - [x] Expose `MithrilStakeDistributionService` functions: `list`, `download`
  - [x] Re-expose `Certifier` service from `mithril-common/certiticate-chain`: `verify_genesis_certificate`, `verify_certificate`, `verify_certificate_chain`
  - [x] Re-expose `mithril-common` types
  - [x] Use optional features in `Cargo.toml` to compile only required dependencies
  - [x] Move to `main.rs` CLI only import/modules
- [x] Make nice Rust documentation with examples and code blocks (Add examples of implementation of the library)
- [x] Create a guide to help developer implement it in their applications in the doc website (add a new chapter in the online documentation)

## Later
- Provide C interface for the library with [cbindgen](https://github.com/mozilla/cbindgen)
- Do we need to split the crate in a binary and a library package?
- Modify the API to provide activity feedback with events/channels for `download` functions (and use them in the commands)

**Comment by ghubertpalo** [comment]
It would be far easier if the `CertificateVerifier` was passed the complete certificate chain and verify it without having to actually perform HTTP requests thought a `CertificateRetriever`. The Aggregator could even have a route `/certificate-chain` that would send the complete certificate chain. This could boost the certificate chain verification performances while making the `CertificateVerifier` more testable.

**Comment by ghubertpalo** [comment]
The idea is to propose a pure (in the software design sense) client library alongside a `Runner` that would take an Aggregator URL and manage to perform needed IOs to verify artifacts (and certificate chain).

**Comment by ghubertpalo** [comment]
**TODO:** 

  * Move the code that downloads the snapshot to a `crate::utils::Downloader`
  * Use channels to report progress to progress bars
  * use the `SnapshotService` to verify certificate chain & snapshot's certificate signature
  * Open & use the `Commands` module in the `main.rs` file (remove call from `lib.rs`)

**Comment by abailly-iohk** [comment]
I ❤️ this feature! Would it be possible/hard to provide a C interface to the library in order to ease integration with other languages?

**Comment by jpraynaud** [comment]
> I ❤️ this feature! Would it be possible/hard to provide a C interface to the library in order to ease integration with other languages?

Yes we could probably use [`cbindgen`](https://github.com/mozilla/cbindgen)  to do this :+1:
