### ISSUE TITLE
P2P Signature Registration PoC

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1300]
## Why
In order to move toward a decentralized Mithril network that would allow multiple aggregators to operate simultaneously.
A P2P network layer could power this new capability and provide a way to exchange signatures between signers and aggregators without relying on a central entity. 

The goal is to create a Proof of Concept for a basic P2P network that would allow multiple aggregator to retrieve the individual signatures posted by signers. A nice to have feature is the ability to deploy a P2P network and at the same time keep the existing centralized implementation: this would allow in the long run to smoothly deploy the P2P network along the existing network.

A good candidate to do so is the **Mithril relay** that we could re-implement:
- Mithril relay is a "proxy" to the historic aggregator.
- Mithril relay is also able to replicate individual signatures sent by the signer to a P2P network (each relay is a peer in the network).

Along the **Mithril relay**, the **Mithril aggregator** has an adapter that is able to retrieve the signatures from the P2P network and make them available to its Certificate producer. 

Here is a draft schema for the architecture of such a P2P **Mithril network**:
![Mithril P2P Network](https://github.com/input-output-hk/mithril/assets/5566665/a783a0a5-8459-45c2-ab68-94ea864f0d67)

**Note**: It is worth mentioning that more work will be needed to work in fully a decentralized setup:
- Capability for an aggregator of peer-discovering other aggregators in the network.
- Capability for an aggregator of retrieving from another aggregator a valid certificate chain.
- Capability for a signer to compute message to sign without communicating with an aggregator.
- Capability for a signer to register its verification keys in a decentralized manner (**with consensus**).

A good P2P candidate library that we intend to evaluate is [libp2p](https://libp2p.io/):
- It has a Rust implementation that is mature and stable
- It provides support for interesting P2P features: **PubSub** [guide](https://docs.libp2p.io/concepts/pubsub/overview/) | [library](https://docs.rs/libp2p/latest/libp2p/gossipsub/)
- It has good documentation and [tutorials](https://docs.rs/libp2p/latest/libp2p/tutorials/ping/index.html)

## What
We want to experiment with P2P and create a PoC to decentralize the signature registration of the signers and make it available to subscribers on a P2P network. In that context, an aggregator subscribed to the signatures can create certificates by relying only on the P2P signatures broadcast. The selected architecture should be versatile enough to not modify the existing signer and aggregator nodes. 

## How

- [x] Make a working prototype of a relay with libp2p **PubSub** (#1326)
- [x] Prepare a dev testnet deployment (#1361)
- [x] Assess problems/difficulties (identified during the implementation phase)

### Later
- Work on other features: client and aggregator use peer discovery to select an aggregator, ...
- Assess what's missing to have multiple aggregators producing certificates
