### ISSUE TITLE
Epic: Light Wallet implementation PoC

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1313]
## Why
We want to create a first PoC of the Light Wallet implementation of Mithril as proposed in the discussion [Implementing Mithril in a light wallet #1273](https://github.com/input-output-hk/mithril/discussions/1273). This first prototype implementation will help us define more precisely the use case and apprehend the underlying technical difficulties and challenges.

## What
In this first PoC, we want to create the **simplest non production ready but working version** of this implementation that will be completely independent of any current light wallet:
- The **Mithril network** is able to sign a representation of the **balances of all addresses** on the Cardano chain (we'll start with the UTxO set, ...).
- The **Mithril aggregator** is able to produce a **cryptographic proof** for the subset of the data signed associated to **one address** (and make it available via its REST API).
- The **Mithril client** is able to **verify the proof** provided by the aggregator, as well as the associated **Mithril certificate chain**, in the **browser**.

#### Run a Mithril client in the browser
- [x] #1254
- [ ] #1141
- [ ] #1311
- [ ] #1284
- [ ] TBD: Mithril client binary/library can list/download and verify a certified UTxO for an address
- [ ] TBD: Implement the WASM Mithril client library in a **fake** light wallet for demonstration

#### What and how to sign/prove UTxO set
- [ ] #1283
- [ ] TBD: How to sign UTxO set and provide a proof for an address PoC

#### Mithril network signs new 'UTxO set' type of signed data

- [ ] TBD: Handle optional type of data in signer/aggregator of a network
- [ ] TBD: Implement new UTxO type of data to sign PoC
- [ ] TBD: Implement new artifact to produce with proof

## Later

> We'll list here all the technical difficulties, challenges, questions that will show up during the prototyping and use them to move toward production ready implementation
