### ISSUE TITLE
Threat modeling and risk analysis

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1350]
## Why
We want to identify and understand the threat model and security risks of the Mithril network.

## What
Prepare a threat model docuemt published on the documentation website.

## How

- [x] Prepare a draft Threat Model page on the documentation website
- [ ] Close existing GitHub discussion and mention the new Threat Model page
- [ ] Make announcement on discord
- [ ] Add dev blog post (if relevant)

## References

* [OWASP Threat modeling process](https://owasp.org/www-community/Threat_Modeling_Process)
* [Ouroboros Network design](https://input-output-hk.github.io/ouroboros-network/pdfs/network-design/network-design.pdf)
