### ISSUE TITLE
Release `2412` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1559]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2412`

### Phase 1: Prepare distribution
- [ ] Update repository dependencies
- [ ] Upgrade minor versions of `mithril-client`/`mithril-client-cli`/`mithril-client-wasm` for breaking change (if needed)
- [ ] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)

### Phase 2: Rollout pre-release distribution
- [ ] Tag and deploy a `2412.0-pre` pre-release distribution on the `pre-release-preview` network 
- [ ] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [ ] Make sure `pre-release-preview` is working as expected 
- [ ] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [ ] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [ ] Prepare a draft PR for rotating the documentation
- [ ] Announce the pre-release on discord channel
- [ ] Announce any breaking change in #cardano-scaling slack channel for pre-release
- [ ] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [ ] Tag and deploy a `2412.0` release distribution on the `pre-release-preview` network
- [ ] Fill highlights and release notes section in the release page on GitHub
- [ ] Make sure `pre-release-preview` is working as expected
- [ ] Update networks compatibility table in release notes
- [ ] Release the `2412.0` distribution
- [ ] Make sure `release-mainnet` is working as expected
- [ ] Make sure `release-preprod` is working as expected
- [ ] Make sure libraries have been published on [crates.io](https://crates.io/)
- [ ] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [ ] Merge the PR for rotating the documentation
- [ ] Announce the release on discord channel (with breaking-change)
- [ ] Announce any breaking/new feature change in:
  - [ ] #cardano-scaling slack channel for release
  - [ ] Dev blog post:
    - [ ] Prometheus endpoint in signer
    - [ ] Logs to `stderr` blog post
