### ISSUE TITLE
Release `2418` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1614]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2418`

## How

> [!IMPORTANT]
> - Breaking change on Mithril client certificate hash
> - Rollout of new Cardano node `8.10`?
> - Upgrade `tokio` `1.37+`

### Phase 1: Prepare distribution
- [x] Update repository dependencies (`tokio` to `1.37.0`)
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)

### Phase 2: Rollout pre-release distribution
- [x] Tag and deploy a `2418.1-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Manual recomputation of certificate hashes of `pre-release-preview` with [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/recompute-certificates-hash)
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Prepare a draft PR for rotating the documentation
- [x] Announce the pre-release on discord channel
- [x] Announce any breaking change in #cardano-scaling slack channel for pre-release
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [x] Tag and deploy a `2418.1` release distribution on the `pre-release-preview` network
- [x] Fill highlights and release notes section in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Release the `2418.1` distribution
- [x] Manual recomputation of certificate hashes of `release-mainnet` with [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/recompute-certificates-hash)
- [x] Manual recomputation of certificate hashes of `release-preprod` with [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/recompute-certificates-hash)
- [x] Make sure `release-mainnet` is working as expected
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Merge the PR for rotating the documentation
- [x] Review and rotate `CHANGELOG.md`
- [x] Announce the release on discord channel (with breaking-change)
- [x] Announce any breaking/new feature change in:
  - [x] #cardano-scaling slack channel for release
  - [x] Dev blog post:
    - [x] TBD
