### ISSUE TITLE
Release `2428` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1810]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2428`

### Phase 1: Prepare distribution
- [x] Upgrade repository dependencies
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)
- [x] Merge a PR for rotating the `CHANGELOG.md` (set the distribution version)
- [x] Create a draft PR for rotating the documentation
- [x] Warmup Cardano node `9.0.0` on `pre-release-preview`
- [x] Warmup Cardano node `9.0.0` on `release-preprod`
- [x] Warmup Cardano node `9.0.0` on `release-mainnet`

### Phase 2: Rollout pre-release distribution
- [x] Tag and deploy a `2428.0-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Switch Cardano database with warmed-up node in `pre-release-preview`
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Run an all green [aggregator stress test](https://github.com/input-output-hk/mithril/actions/workflows/aggregator-stress-test.yml) in the CI
- [x] ~~Run a Cardano transaction prover benchmark:~~
  - [x] ~~Store results in the issue~~
  - [x] ~~Make sure that there is no performance drop since last release~~
- [x] Announce the pre-release on discord channel
- [x] ~~Announce any breaking change in #cardano-scaling slack channel for pre-release~~
- [x] ~~Announce any breaking change in #mithril-lace slack channel for pre-release~~
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [x] Tag and deploy a `2428.0` release distribution on the `pre-release-preview` network
- [x] Fill highlights and release notes section in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Release the `2428.0` distribution
- [x] Switch Cardano database with warmed-up node in `release-mainnet`
- [x] Make sure `release-mainnet` is working as expected
- [x] Switch Cardano database with warmed-up node in `release-preprod`
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Merge the PR for rotating the documentation
- [x] Merge a PR for rotating the `CHANGELOG.md` (release date of the distribution)
- [x] Announce the release on discord channel (with breaking-change)
- [x] ~~Announce any breaking/new feature change in:~~
  - [x] ~~#cardano-scaling slack channel for release~~
  - [x] ~~#mithril-lace slack channel for release~~
  - [x] ~~Dev blog post:~~
    - [x] ~~TBD~~

**Comment by jpraynaud** [comment]
Here is the process to warm up the nodes and switch of the database:
```bash
# Select the Mithril network
## Connect to pre-release-preview
export AGGREGATOR_ENDPOINT=https://aggregator.pre-release-preview.api.mithril.network/aggregator
export GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/pre-release-preview/genesis.vkey)

### release-preprod
export AGGREGATOR_ENDPOINT=https://aggregator.release-preprod.api.mithril.network/aggregator
export GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/release-preprod/genesis.vkey)

### release-mainnet 
export AGGREGATOR_ENDPOINT=https://aggregator.release-mainnet.api.mithril.network/aggregator
export GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/release-mainnet/genesis.vkey)

# Phase 1: Warmup a temporary Cardano node from a Mithril snapshot
## Create temp dir
rm -rf /home/curry/data/temp
mkdir -p /home/curry/data/temp
cd /home/curry/data/temp

## Download Mithril client
wget https://github.com/input-output-hk/mithril/releases/download/2423.0/mithril-2423.0-linux-x64.tar.gz
tar xzf mithril-2423.0-linux-x64.tar.gz mithril-client
chmod u+x mithril-client
./mithril-client --version

## Download latest snapshot
./mithril-client snapshot download latest

## Restore the Cardano node
docker run -d --name cardano-node-warmup -v cardano-node-ipc:/ipc -v cardano-node-data:/data --mount type=bind,source="/home/curry/data/temp/db",target=/data/db/ -e NETWORK=${NETWORK} ghcr.io/intersectmbo/cardano-node:9.0.0
docker logs -f --tail 100 cardano-node-warmup

# Phase 2: Switch Cardano database from the main node with the warmed-up one
## Copy Cardano database to aggregator
docker stop cardano-node-warmup
docker stop cardano-node-aggregator
mv /home/curry/data/$NETWORK/mithril-aggregator/cardano/db /home/curry/data/$NETWORK/mithril-aggregator/cardano/db.bak
mv /home/curry/data/temp/db /home/curry/data/$NETWORK/mithril-aggregator/cardano/db
sudo chown -R curry /home/curry/data/$NETWORK/mithril-aggregator/cardano/db
sudo chgrp -R curry /home/curry/data/$NETWORK/mithril-aggregator/cardano/db
docker start cardano-node-aggregator
docker logs -f --tail 100 cardano-node-aggregator

## Cleanup directory (when node is back up)
docker rm cardano-node-warmup
rm -rf /home/curry/data/$NETWORK/mithril-aggregator/cardano/db.bak
cd /home/curry/
rm -rf /home/curry/data/temp
```
