### ISSUE TITLE
Release `2430` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1830]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2430`

> [!IMPORTANT]
> - [x] Activate Cardano transactions certification in `release-preprod` and `pre-release-preview`
> - [x] Upgrade to Cardano node `9.1`
> - [x] Upgrade `release-mainnet` disk

### Phase 1: Prepare distribution
- [x] Upgrade repository dependencies
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)
- [x] Merge a PR for rotating the `CHANGELOG.md` (set the distribution version)
- [x] ~~Create a draft PR for rotating the documentation~~
- [x] Merge a PR that upgrades `release-mainnet` VM data disk to `pd-balanced`

### Phase 2: Rollout pre-release distribution
- [x] Activate the certification of Cardano transaction in `pre-release-preview`
- [x] Tag and deploy a `2430.0-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Run an all green [aggregator stress test](https://github.com/input-output-hk/mithril/actions/workflows/aggregator-stress-test.yml) in the CI
- [x] ~~Run a Cardano transaction prover benchmark:~~
  - [x] ~~Store results in the issue~~
  - [x] ~~Make sure that there is no performance drop since last release~~
- [x] Announce the pre-release on discord channel
- [x] ~~Announce any breaking change in #cardano-scaling slack channel for pre-release~~
- [x] ~~Announce any breaking change in #mithril-lace slack channel for pre-release~~
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [x] Announce upcoming downtime of `30 minutes` on the `release-mainnet` aggregator for maintenance in discord channel
- [x] Tag and deploy a `2430.0` release distribution on the `pre-release-preview` network
- [x] Fill highlights and release notes section in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Activate the certification of Cardano transaction in `release-preprod`
- [x] 🔥 Begin the `release-mainnet` VM data disk upgrade 
- [x] Release the `2430.0` distribution
- [x] 🔥 Complete the `release-mainnet` VM data disk upgrade 
- [x] Make sure `release-mainnet` is working as expected
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] ~~Merge the PR for rotating the documentation~~
- [x] Merge a PR for rotating the `CHANGELOG.md` (release date of the distribution)
- [x] Announce the release on discord channel (with breaking-change)
- [x] ~~Announce any breaking/new feature change in:~~
  - [x] ~~#cardano-scaling slack channel for release~~
  - [x] ~~#mithril-lace slack channel for release~~
  - [x] Dev blog post:
    - [x] Activation of Cardano transaction in `release-preprod` and `pre-release-preview`
