### ISSUE TITLE
Mithril signature diffusion with Cardano network layer PoC

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1837]
## Why
We want to create a PoC for implementing the Cardano network decentralized message queue in the Mithril network.
The decentralized message queue is not fully specified and not implemented: this means that we will have to simulate it.

The outcome of the PoC will be:
- Can we implement the n2c mini protocols of the decentralized message queue in the signer and aggregator.
- Assess which type of requirements will be needed when implementing the Cardano decentralized message queue.
- Assess which type of modification will be needed on the long run in the signer and aggregator.

## What
Implement a PoC where signatures are transmitted from a signer to an aggregator through a simulated decentralized message queue. 

Ideally, we want to demonstrate a Mithril devnet fully operating with signature diffusion by the simulated Cardano message queue.

## How

- [x] Abstract interactions:
  - [x] between the signer and the Cardano message queue with a Publisher (sending signatures)
  - [x] between the Cardano message queue and the aggregator with a Consumer (receiving signatures)
- [x] Implement the Consumer in the aggregator:
  - [x] Run the consumer in a new thread
  - [x] The consumer constantly reads the local Unix socket
  - [x] When a new single signature is available, it is send to the Certifier service (`register_single_signature` function)
- [x] Implement the Publisher in the signer:
  - [x] Replace/adapt the aggregator client to send signatures on a local Unix socket
- [x] Simulated Cardano network decentralized message queue with a separate process (new crate)
  - [x] Simulate the Cardano server behavior of the Local Message Submission mini protocol:
    - [x] Open a server on a local Unix socket
    - [x] Upon reception of a call with a signature on the server write to the signature to a channel
  - [x] Simulate the Cardano server behavior of the Local Message Notification mini protocol:
    - [x] Open a server on a local Unix socket
    - [x] Upon reception of a call to retrieve the next signatures read the signature from the channel (if any)

## Questions/Resources
- How to implement a simple Cardano network decentralized message queue simulator? 
  - use `warp` and make it listen on a Unix socket as in https://github.com/masonforest/warp/commit/9b15a710dbe7d6b36c61d04830c2b2989e89a5e6
- How to send HTTP requests on a local Unix socket?
  - Use `curl` with `--unix-socket` option
- Serialize/Deserialize Cbor hex encoded messages (not in first version)???
