### ISSUE TITLE
Release `2442` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1943]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2442`

> [!IMPORTANT]
> - [x] Ship new era
> - [x] :fire: Breaking-change in client for Mithril stake distribution protocol message computation
> - [x] Make client for Cardano transactions stable
> - [x]  #2003 
> - [ ] Activate Cardano stake distribution certification:
>   - [x] in `pre-release-preview`
>   - [x] in `release-preprod`
>   - [ ] in `release-mainnet`
> - [x] Upgrade to Cardano node `9.2.1`:
>   - [x] in `pre-release-preview`
>   - [x] in `release-preprod`
>   - [x] in `release-mainnet`

Distribution +1:
> [!NOTE]
> - [ ] Make client for Cardano stake distribution stable

### Phase 1: Prepare distribution
- [x] Test backward compatibility with previous signer version(s)
- [x] Upgrade repository dependencies (with [runbook](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/upgrade-repository-dependencies/README.md))
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)
- [x] Merge a PR for rotating the `CHANGELOG.md` (set the distribution version)
- [x] Create a draft PR for rotating the documentation

### Phase 2: Rollout pre-release distribution
- [x] Update the configuration of `pre-release-preview`:
  - [x] Upgrade the Cardano node version to `9.2.1`
  - [x] Activate the certification of the `Cardano Stake Distribution`
- [x] Tag and deploy a `2442.0-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill 'Highlights' and release notes section in the pre-release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Run an all green [aggregator stress test](https://github.com/input-output-hk/mithril/actions/workflows/aggregator-stress-test.yml) in the CI
- [x] Run a Cardano transaction prover benchmark:
  - [x] Store results in the issue
  - [x] Make sure that there is no performance drop since last release
- [x] Announce the pre-release on discord channel
- [x] Announce any breaking change in:
  - [x] ~~#cardano-scaling slack channel for pre-release~~
  - [x] ~~#mithril-lace slack channel for pre-release~~
  - [x] ~~#blockfrost-scaling slack channel for pre-release~~
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [x] Tag and deploy a `2442.0` release distribution on the `pre-release-preview` network
- [x] Fill highlights and release notes section in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Update the configuration of `release-preprod`:
  - [x] Upgrade the Cardano node version to `9.2.1` in `release-preprod`
  - [x] Activate the certification of the `Cardano Stake Distribution`
- [x] Update the configuration of `release-mainnet`:
  - [x] Upgrade the Cardano node version to `9.2.1` in `release-mainnet`
- [x] Release the `2442.0` distribution
- [x] Make sure `release-mainnet` is working as expected
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Merge the PR for rotating the documentation
- [x] Merge a PR for rotating the `CHANGELOG.md` (updating the release date of the distribution)
- [x] Announce the release on discord channel (with breaking-change, upcoming features activation, ...)
- [x] Announce any breaking/new feature change in:
  - [x] ~~#cardano-scaling slack channel for release~~
  - [x] ~~#mithril-lace slack channel for release~~
  - [x] ~~#blockfrost-scaling slack channel for release~~
- [x] Dev blog post:
  - [x] Activation of the Cardano Stake Distribution certification in `pre-release-preview` and `release-preprod`
    
### Phase 4: Activate features
- [ ] Cardano stake distribution:
  - [ ] When signer release `>= 0.2.182` (`2437.1`) is run by `> 95%` of the stake (within 2 weeks, or abort), 
  - [ ] Activate the certification of Cardano stake distribution in `release-mainnet`
  - [ ] Restart the `release-mainnet` deployment in the CI
  - [ ] Make sure `release-mainnet` is working as expected
  - [ ] Announce the release on discord channel
  - [ ] Dev blog post: Activation of Cardano stake distribution in `release-mainnet`

**Comment by jpraynaud** [comment]
## Cardano transactions prover benchmark

> [!NOTE]
> run on GCP with `e2-highmem-2` machine with `2` vCPUs and `15GB` of RAM
> not during Cardano database snapshotting

- Benchmark results:

| **total_requests** | **concurrency** | **transactions/request** | **requests/s** |
|--------------------|-----------------|--------------------------|----------------|
| 500                | 50              | 1                        | 56.11          |
| 500                | 50              | 10                       | 41.44          |
| 500                | 50              | 20                       | 33.54          |
| 500                | 50              | 30                       | 30.91          |
| 500                | 50              | 40                       | 27.23          |
| 500                | 50              | 50                       | 24.67          |

vs previous results

| **total_requests** | **concurrency** | **transactions/request** | **requests/s** |
|--------------------|-----------------|--------------------------|----------------|
| 500                | 50              | 1                        | 58.71          |
| 500                | 50              | 10                       | 49.19          |
| 500                | 50              | 20                       | 39.17          |
| 500                | 50              | 30                       | 34.11          |
| 500                | 50              | 40                       | 29.21          |
| 500                | 50              | 50                       | 24.39          |

- Command run:
```bash
# Aggregator endpoint
export AGGREGATOR_ENDPOINT=https://aggregator.pre-release-preview.api.mithril.network/aggregator

# Transactions file to prove
export TRANSACTIONS_FILE=transactions-preview.txt

# Transactions proved per request range definition
export TRANSACTIONS_PER_REQUEST_MIN=0
export TRANSACTIONS_PER_REQUEST_MAX=50
export TRANSACTIONS_PER_REQUEST_STEP=10

# Apache benchmark total request sent per benchmark
export AB_TOTAL_REQUESTS=500

# Apache benchmark concurrency level range definition
export AB_CONCURRENCY_MIN=50
export AB_CONCURRENCY_MAX=50
export AB_CONCURRENCY_STEP=50

# Run the benchmark:
./benchmark-aggregator-prover.sh
```

- Command result:
```bash
MITHRIL AGGREGATOR PROVER ROUTE BENCHMARK

>> Aggregator endpoint: https://aggregator.pre-release-preview.api.mithril.network/aggregator
>> Aggregator route: /proof/cardano-transaction
>> Transactions file: transactions-preview.txt
>> Transactions available: [100]
>> Transactions per request range: [0 10 20 30 40 50]
>> AB concurrency range: [50]
>> AB total requests per run: [500]
>> AB total runs: 6
>> Output file: benchmark.csv

>> [#1/6] Running stress test with 500 requests with 1 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (56.11 requests/s)

>> [#2/6] Running stress test with 500 requests with 10 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (41.44 requests/s)

>> [#3/6] Running stress test with 500 requests with 20 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (33.54 requests/s)

>> [#4/6] Running stress test with 500 requests with 30 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (30.91 requests/s)

>> [#5/6] Running stress test with 500 requests with 40 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (27.23 requests/s)

>> [#6/6] Running stress test with 500 requests with 50 transactions per request and 50 concurrency
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests
>>>> Success (24.67 requests/s)

>> Benchmark completed:

total_requests,concurrency,transactions/request,requests/s
500,50,1,56.11
500,50,10,41.44
500,50,20,33.54
500,50,30,30.91
500,50,40,27.23
500,50,50,24.67
```
