### ISSUE TITLE
Redesign website and improve documentation

### ISSUE THREAD

**Issue by rezabaram** [input-output-hk/mithril#2051]
## Why
The documentation website needs to be restructured and enhanced to give access to resources to users depending on who they are. Also the home page needs to be redesigned to provide more information.

## What 
Enhance documentation structure and redesign home page.

## How

- [x] Enhance the documentation structure
  - [x] User manual section
  - [x] About Mithril section
- [ ] Redesign the home page
