### ISSUE TITLE
Release `2450` distribution

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#2124]
## Why
In order to deploy new features, improvements and bug fixes, we need to release a new distribution.

## What
Create and release a new distribution `2450`

> [!IMPORTANT]
> - [x] 🔥 Announce breaking change in clients
> - [x] 🔥 recompute certificate chain
>   - [x] in `pre-release-preview`
>   - [x] in `release-preprod`
>   - [x] in `release-mainnet`
> - [x] Upgrade to Cardano node `10.1.3`
>   - [x] in `pre-release-preview`
>   - [x] in `release-preprod`
>   - [x] in `release-mainnet`
> - [x] Pre-built binaries have execution rights
> - [x] New NodeJS npm package

Distribution +1:
> [!NOTE]
> - [ ] Activate Cardano stake distribution certification:
>   - [ ] in `release-mainnet`
> - [ ] TBD

### Phase 1: Prepare distribution
- [x] Run a [backward compatibility test](https://github.com/input-output-hk/mithril/actions/workflows/nightly-backward-compatibility.yml) in the CI
- [x] Upgrade repository dependencies (with [runbook](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/upgrade-repository-dependencies/README.md))
- [x] Check that all minor versions of all crates have been bumped for breaking change (if needed)
- [x] Check if versions of repository linked crates are correct for publication to `crates.io`(`mithril-common`, `mithril-client`)
- [x] Check if Cardano minimum supported versions in `networks.json` must be updated following the [runbook](https://github.com/input-output-hk/mithril/tree/main/docs/runbook/maintain-cardano-min-versions-file#readme)
- [x] Merge a PR for rotating the `CHANGELOG.md` (set the distribution version)
- [x] Create a draft PR for rotating the documentation

### Phase 2: Rollout pre-release distribution
- [x] Update the configuration of `pre-release-preview`:
  - [x] Upgrade the Cardano node version to `10.1.3` in `pre-release-preview`
- [x] Tag and deploy a `2450.0-pre` pre-release distribution on the `pre-release-preview` network 
- [x] Fill highlights, distributions compatibility and release notes sections in the pre-release page on GitHub
- [x] Recompute the [certificate chain](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/recompute-certificates-hash/README.md) of `pre-release-preview`
- [x] Make sure `pre-release-preview` is working as expected 
- [x] Make sure libraries version `next` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Run an all green [client multi-platform test](https://github.com/input-output-hk/mithril/actions/workflows/test-client.yml) in the CI
- [x] Run an all green [aggregator stress test](https://github.com/input-output-hk/mithril/actions/workflows/aggregator-stress-test.yml) in the CI
- [x] Run a Cardano transaction prover benchmark:
  - [x] Store results in the issue
  - [x] Make sure that there is no performance drop since last release
- [x] Announce the pre-release on discord channel
- [x] Announce any breaking change in:
  - [x] #cardano-scaling slack channel for pre-release
  - [x] #mithril-lace slack channel for pre-release
  - [x] #blockfrost-scaling slack channel for pre-release
  - [x] ~~#minotaur-mithril slack channel for pre-release~~
  - [x] Cardano Foundation IBC bridge team
- [x] Wait for at least `3` signers running the new version (could be more if era change is tested) over at least `2` epochs

### Phase 3: Rollout release distribution
- [x] Tag and deploy a `2450.0` release distribution on the `pre-release-preview` network
- [x] Fill highlights, distributions compatibility and release notes sections in the release page on GitHub
- [x] Make sure `pre-release-preview` is working as expected
- [x] Update networks compatibility table in release notes
- [x] Update the configuration of `release-preprod`:
  - [x] Upgrade the Cardano node version to `10.1.3` in `release-preprod`
- [x] Update the configuration of `release-mainnet`:
  - [x] Upgrade the Cardano node version to `10.1.3` in `release-mainnet`
- [x] Release the `2450.0` distribution
- [x] Stop aggregators:
  - [x] `release-mainnet`
  - [x] `release-preprod` 
- [x] Recompute the [certificate chain](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/recompute-certificates-hash/README.md) of `release-mainnet`
- [x] Make sure `release-mainnet` is working as expected
- [x] Recompute the [certificate chain](https://github.com/input-output-hk/mithril/blob/main/docs/runbook/recompute-certificates-hash/README.md) of `release-preprod`
- [x] Make sure `release-preprod` is working as expected
- [x] Make sure libraries have been published on [crates.io](https://crates.io/search?q=mithril)
- [x] Make sure libraries version `latest` have been published on [npm registry](https://www.npmjs.com/package/@mithril-dev/mithril-client-wasm)
- [x] Merge the PR for rotating the documentation
- [x] Merge a PR for rotating the `CHANGELOG.md` (updating the release date of the distribution)
- [x] Announce the release on discord channel (with breaking-change, upcoming features activation, ...)
- [x] Announce any breaking/new feature change in:
  - [x] #cardano-scaling slack channel for release
  - [x] #mithril-lace slack channel for release
  - [x] #blockfrost-scaling slack channel for release
  - [x] ~~#minotaur-mithril slack channel for pre-release~~
  - [x] Cardano Foundation IBC bridge team
- [x] Dev blog post:
  - [x] Distribution `2450`

### Phase 4: Activate features
- [ ] Cardano stake distribution:
  - [ ] When signer release `>= 0.2.182` (`2437.1`) is run by `> 95%` of the stake (within 2 weeks, or abort), 
  - [ ] Activate the certification of Cardano stake distribution in `release-mainnet`
  - [ ] Restart the `release-mainnet` deployment in the CI
  - [ ] Make sure `release-mainnet` is working as expected
  - [ ] Announce the release on discord channel
  - [ ] Dev blog post: Activation of Cardano stake distribution in `release-mainnet`
