### ISSUE TITLE
Configure GCP storage expiration policy

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#270]
We need to configure [GCP storage expiration policy](https://cloud.google.com/storage/docs/using-bucket-lock#set-policy) and [GCP Object Lifecycle Management](https://cloud.google.com/storage/docs/lifecycle-configurations#gsutil) for the snapshot archives that will start to stack as the new Mithril Aggregator runtime has been deployed:

⚠ Once the feature period is activated, all the files older than it will be deleted. It will also be impossible to manually delete files

ℹ This period can be adjusted later if needed with these commands, for a retention of `14` days:
* Update `Retention Period`:
```bash
gsutil retention set 14d gs://cardano-testnet
```
* Update `Lifecycle Management Rule`:
```bash
cat >> gsutil-lifecycle-rule.json <<EOF
{
"lifecycle": {
  "rule": [
  {
    "action": {"type": "Delete"},
    "condition": {
      "age": 14
    }
  }]
 }
}
EOF

gsutil lifecycle set gsutil-lifecycle-rule.json gs://cardano-testnet
```

**Tasks**:
- [x] Create a `cardano-mainnet` bucket and move the `gs://cardano-testnet/mainnet.tar.gz` and 
`gs://cardano-testnet/mainnet.tar.gz.gpg` files to it
- [x] Cleanup `cardano-testnet` bucket with stale snapshots
- [x] Activate a `14` days retention policy/lifecycle management for the uploaded snapshot archives on the `cardano-testnet` bucket (this means `~90` snapshots max on bucket or `~380GB` of storage)
