### ISSUE TITLE
Handle the `poolId` along with `party_id` in Core/Aggregator/Signer

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#276]
### Need
In order to use correctly the stake distribution retrieved from the Cardano node, we need to handle properly and match:
* The `poolId`: unique identifier of the SPO in the stake distribution
* The `party_id`: unique identifier used in the Mithril protocol

### Solution
* The `party_id` in the Mithril nodes will store the `poolId` from the Cardano node
* The `party_id` will be removed from the `mithril-core` library

### Tasks
- [x] Remove the `party_id` in `mithril-core` interface (and recompute it inside the lib with custom sort based on `stake` and `verification_key`) (Done in #279)
- [x] Switch the `party_id: u64` with `party_id: String` in `open-api.yaml`
- [x] Switch the `party_id: u64` with `party_id: String` in `mithril-common`
- [x] Switch the `party_id: u64` with `party_id: String` in `mithril-aggregator`
- [x] Switch the `party_id: u64` with `party_id: String` in `mithril-signer`
- [x] Switch the `party_id: u64` with `party_id: String` in `protocol-demo`
- [ ] Reset (if needed) associated data stores on GCP
