### ISSUE TITLE
Implement certificate chain Aggregator/Signer/Client

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#316]
## Context

In order to provide the expected level of security, the `certificates` produced by the Aggregator must be combined as a `chain of certificates` that will provide a way to validate that the `stake distribution` used to create the `multi signatures` is valid.

A diagram that explains the structure of the chain is available on the [`miro board`](https://miro.com/app/board/o9J_lKq5Szc=/?moveToWidget=3458764528672303874&cot=14).

This issue will focus only on the `standard` part of the `certificate chain`. The `genesis` part of it will be done in another issue.

### Tasks
- [x] Remove the unused `previous_hash` from the `CertificatePending` entity
- [x] Implement the epoch offsets mechanism in the Aggregator and the Signer with `Retrieval` and `Recording` offsets (see #287)
- [x] Update the `Beacon` to handle the gracefully an epoch offset overflow
- [x] Update the `Certificate` entity structure to align it with the chain mechanism
- [x] Update the `OpenAPI` specification accordingly
- [x] Update the `Aggregator` to use this new `Certificate` structure
- [x] Update the `Signer` to use this new `Certificate` structure
- [x] Update the `Client` to use this new `Certificate` structure
- [x] Use real `Next Epoch Aggregate Verification Key` in the signed message (`Signer` and `Aggregator`)
- [x] Implement the `Certificate Chain` production in the `Aggregator`
- [x] Implement the `Certificate Chain` verification in the `Client`
- [x] Update the `End to End Test Runner` to wait for the creation of a long enough `Certificate Chain`
- [x] Update the `End to End Test Runner` to handle `Stake Distribution` update
- [x] Reset the `Certificate Store` on the `GCP Aggregator`
