### ISSUE TITLE
Configure SSL certificate for Mithril Aggregator GCP

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#324]
### Issue
Provide a SSL connection to the REST API of the Aggregator

### Tasks
- [x] Add a [`Traefik`](https://github.com/traefik/traefik) reverse proxy in front of the `mithril-aggregator` container
- [x] Handle SSL certificate creation/renewal with [`Let's encrypt`](https://letsencrypt.org/)
- [x] Update all the existing non secure endpoint of the API to `https`
