### ISSUE TITLE
Add Store Protocol Parameters in Aggregator

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#385]
### Issue
This store is needed in the Aggregator to keep track of the `Protocol Parameters`.

These `Protocol Parameters` are then stored in the `Protocol Initializer Store` of the Signer. Thus, it does not need a dedicated store for keeping track of these parameters.

### Tasks
- [X] A `Protocol Parameters Store` in the Aggregator
- [X] Update configuration where needed
- [X] Update documentation where needed
- [x] Add `Protocol Parameters` as a configuration
- [x] Store `Protocol Parameters` in runtime
- [x] Use `Protocol Parameters` in multi signer
- [x] Add `next_protocol` field in `Pending Certificate`
