### ISSUE TITLE
Merkle Tree Discussion and Todo

### ISSUE THREAD

**Issue by spaceships** [input-output-hk/mithril#4]
- [x] Avoiding hashing the leaves. Iñigo asked whether we could avoid hashing the leaves of the tree to save space. Our Merkle Tree does not take ownership of the leaves (field element + u64 for the stake). Hashing them is a space win, since the actual leaves then dropped by the caller. Do you agree?
- [ ] Merkle Trees with a non-power-of-2 number of leaves contain nodes where there is only one child. We think that the standard way of handling this case is to hash the single child. Do you agree?
- [ ] Using our own Merkle Tree implementation. We didn't have a lot of confidence in the Ark MT implementation. We had specific requirements at first, because of Poseidon, but when we dropped that, we overlooked the fact that we could use a library. We think it's worth investigating, it will lower maintenance cost and complexity of the library. @abakst will look into this.
