### ISSUE TITLE
Simplify Store Configuration in Aggregator/Signer

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#422]
### Issue
Simplify configuration of stores in Aggregator and Signer

### Tasks
- [x] Simplify stores config with only one configurable prefix
- [x] Update test end to end
- [x] Update devnet
- [x] Update GCP infra
- [x] Update the associated documentations (website)
