### ISSUE TITLE
Aggregator is stuck in "Signing" state when epoch changes

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#431]
### Issue
Apparently, after an epoch change, the Aggregator is stuck in `SIGNING` state and does not go back to `IDLE` state as expected.
It seems that an error when trying to drop the `Pending Certificate` is preventing the state transition

### Logs on GCP
```
mithril-aggregator_1                | {"msg":"================================================================================","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.264023249Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"new cycle","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.264227275Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"state SIGNING","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.264364965Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"checking if there is a new beacon","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.26448826Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"checking if there is a new beacon: Beacon { network: \"testnet\", epoch: Epoch(224), immutable_file_number: 3070 }","v":0,"name":"slog-rs","level":20,"time":"2022-08-18T07:40:59.32957801Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"drop pending certificate","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.329853796Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"General(\"no certificate pending for the given beacon\")","v":0,"name":"slog-rs","level":50,"time":"2022-08-18T07:40:59.330276027Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"Sleeping for 60000 ms","v":0,"name":"slog-rs","level":30,"time":"2022-08-18T07:40:59.330491275Z","hostname":"efa9bd08ae57","pid":1}
mithril-aggregator_1                | {"msg":"certificate_pending","v":0,"name":"slog-rs","level":20,"time":"2022-08-18T07:41:02.251562986Z","hostname":"efa9bd08ae57","pid":1}

```

### Explanation

* The transition from `SIGNING` to `IDLE` is not done when an error occurs during the drop of the `Pending Certificate`
* This error occurs because the `Pending Certificate` has already been dropped during a previous cycle of the runtime
* The previous cycle has failed (in that case because of a `GCP` errorand thus the state machine stayed in the `SIGNING` state
```
mithril-aggregator_1                | {"msg":"SnapshotUploader(\"Other(\\\"{\\\\n  \\\\\\\"error\\\\\\\": {\\\\n    \\\\\\\"code\\\\\\\": 403,\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"Object 'cardano-testnet/testnet.1a36fa12a9eb72181c722f6e33d40a2868d9bc69830100d1a2faed74f30aba1e.tar.gz' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2022-08-31T07:33:32.694335-07:00\\\\\\\",\\\\n    \\\\\\\"errors\\\\\\\": [\\\\n      {\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"Object 'cardano-testnet/testnet.1a36fa12a9eb72181c722f6e33d40a2868d9bc69830100d1a2faed74f30aba1e.tar.gz' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2022-08-31T07:33:32.694335-07:00\\\\\\\",\\\\n        \\\\\\\"domain\\\\\\\": \\\\\\\"global\\\\\\\",\\\\n        \\\\\\\"reason\\\\\\\": \\\\\\\"forbidden\\\\\\\"\\\\n      }\\\\n    ]\\\\n  }\\\\n}\\\\n\\\")\\n\")","v":0,"name":"slog-rs","level":50,"time":"2022-08-17T17:11:52.525915034Z","hostname":"efa9bd08ae57","pid":1}

```

### Tasks

- [x] Avoid snapshot file collisions on GCP (by adding the epoch in the file name)
- [x] Clarify error messages when dropping `Pending Certificate`
- [x] Gracefully handle error when dropping `Pending Certificate` that should lead to state transition
- [x] Check that a snapshot for the current `Beacon` is not already done before transitioning to `SIGNING` state
