### ISSUE TITLE
Finalize open-sourcing of repository

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#454]
## Issue
Following open sourcing of the repository, we need to finalize some tasks

## Tasks
* [x] Make Docker repository public ([`mithril-client`](https://github.com/orgs/input-output-hk/packages/container/mithril-client/settings))
* [x] Add missing comments in repository code for Rust (add `#![warn(missing_docs)]` in `lib.rs` and `main.rs` files)
* [x] Clean repository unused/stale branches ([see](https://github.com/input-output-hk/mithril/branches/stale))
* [x] Create discord channel on IOG server and add it in the documentation 
* [x] Add visitors statistics tag on explorer website
* [x] Add Github templates for issues and PR
* [x] Align/Clean README (sub sections only)
* [x] Add a `Dev Blog` section to the documentation website
