### ISSUE TITLE
Add auto pruning in stores

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#504]
### Issue
In order to keep stores with low overhead, we need to prune some stores of the Aggregator/Signers (depending on business rules)

### Tasks
In Aggregator:
- [X] Protocol Parameters (5 last epochs)
- [X] Single Signatures (5 last epochs)
- [X] Verification Keys (5 last epochs)
- [X] Stake (5 last epochs)

In Signer:
- [X] Protocol Initializer (5 last epochs)
- [X] Stake (5 last epochs)

Documentation:
- [x] Aggregator
- [x] Signer

**Comment by ghubertpalo** [comment]
The retention period should be configurable per environment so dev & testing env could keep data for debug purposes.
