### ISSUE TITLE
Optimize Snapshot Digest Computation

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#510]
## Issue
We need to optimize the computation of the `Snapshot Digest` that takes place on the Signer and Aggregator.
To do so, we can make use of memoization so that the CPU intensive part of the computation is done only once (do not do the same hashing of the immutable files and use a cached version instead)

## Tasks

- [x] Compute hash of each immutable file and store them in a cache
- [x] Compute the digest of the immutable files by concatenating their respective hash in a deterministic order (depending on the immutable file number) and hashing this concatenation
- [x] Store/load the already computed hash in a store (would help when node is restarted)?
