### ISSUE TITLE
Add versioning to documentation

### ISSUE THREAD

**Issue by Alenar** [input-output-hk/mithril#555]
# Issue

We need to handle versioning for the documentation website to be able to keep the documentation for the last released version while being able to work on the next version documentation.
We also needs to be able to release blog posts without requiring to release a new version (ie: to advertise for an upcoming change) meaning that simply using two websites, one for the next version one for the current version, in the github pages won't be without frictions.

We can do something similar to what docusaurus use _([see the "canary" version in their version dropdown](https://docusaurus.io/docs/))_ :
Use their version system to have two versions in the website at the same time: a `current` version in a `docs/versioned_docs/current/` folder meanwhile the `docs/root/` folder would be the `next`, work in progress 🚧 ,  version.
An user would land by default on the `current` version of the website but could change at anytime to the `next` version using the docusaurus auto-generated version dropdown.

# Tasks

- [x] Use [docusaurus version tagging command](https://docusaurus.io/docs/versioning#tagging-a-new-version) to create a `current` version (it will copy the content of `docs/root/` in a `docs/versioned_docs/current/` folder).
- [x] Update `docusaurus.config.js` to label the `current` version with a number from a `currentVersion.json` file.
- [x] Add a makefile recipe `update-current` that: 1 - wipe the `docs/versioned_docs/current/` folder, 2 - copy the content of `docs/root/` to `docs/versioned_docs/current/`.

# Questions

- When do we update the current version ?
  - With the (pre ?)release so the updated doc is included in the git tag but meaning that the previous version doc will be labelled at the  for some time until we finish to test & qualify its artifacts ?
  - After a release so the user never loose access to the current doc but the doc won't be included in the git release tag ?
