### ISSUE TITLE
CI does not trigger for PR from forks

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#597]
## Issue
The CI workflow does not trigger for PR produced from a fork of the repository, thus not producing artifacts for the commit when it is merged
See https://github.com/input-output-hk/mithril/pull/591 & https://github.com/input-output-hk/mithril/actions/runs/3477670358

## Todo:

- [ ] 1. Switch `pull_request` event trigger for the `ci` and `docs` workflows (see #613)
- [ ] 2. Make a PR from a remote repository to see if this issue is fixed
- [ ] 3. Make a test release to see if the current process still works with packages from workflows using the `pull_request` event trigger.
