### ISSUE TITLE
Implement backward/forward compatible API messages

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#688]
## Issue 
We want to handle backward compatibility of messages exchanged via the API in order to avoid breaking changes
To do so, we will separate API messages from business entities. Many of our current entities are already used as messages.
We need to create a new layer that handles backward compatibility of API messages and import/export to business entities.
The API messages will be responsible for handling backward/forward compatibility.

![Mithril (1)](https://user-images.githubusercontent.com/5566665/212922867-73c635e2-c957-4be9-b363-f1318425b457.jpg)

## To do

- [x] Identify all the entities that must be associated to a message
- [x] #689
- [x] #693
- [x] #695
- [x] #696
- [x] #697
- [x] #698
- [x] #699
- [x] #705
- [x] Update API / OpenAPI version
- [x] Decide how to implement messages sub types that are currently entities?

## Maybe later
- [ ] Add a wiki page with best practices on how to handle API messages updates, when they introduce breaking changes, and how to golden test the modifications
