### ISSUE TITLE
Implement signer versions deployment monitoring

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#718]
## Issue
We have created an [ADR](https://mithril.network/doc/adr/4) for the **Update Strategy for Mithril Network**. We have decided to use a mechanism of **Era Activation Marker** that allows to activate some code synchronously on the signers and aggregator nodes. The purpose of this issue is to implement the monitoring of the signer node versions in order to compute the share of the total Mithril stakes that can run the new behavior.

## To do

- [x] #737
- [x] #738
- [x] #739
- [x] #740
- [x] #741
- [x] #742 (pool id, stakes, epoch, node-version)
- [x] #743

## Later
- [ ] #744 (retention delay)
- [ ] Create the signature registration event
- [ ] Create the multi-signature created event (and other monitoring that can be implemented in the runtime)
- [ ] Add route(s) on the aggregator that returns the consolidated data from the events recorded
- [ ] Design a `mithril-monitor` node that would scan and monitor the network?

## Depends on 
#476
