### ISSUE TITLE
Design and implement generic signing/verification entity services

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#780]
## Issue
Design the interfaces and scope of entity services that will be implemented in the aggregator, signer and client nodes to handle different types of data. Each entity service should be able to compute a message given a custom beacon and provide that message to the signing engine. The signing engine is agnostic of the messages that are signed. The certificate chain should be modified to provide a certificate for each new message of each type of data, and link that certificate to the first certificate of the epoch (which will sign the Mithril stake distribution used in the next epoch)

## To do

- [x] #847
- [x] #868 
- [x] #851
- [x] #852
- [x] #869 
- [x] #853
- [x] #854
- [x] #848 
- [x] #849
- [x] #850
- [x] #870
- [x] #871
- [x] #933 
- [x] Cleanup the Multi-signer state
- [x] Adapt the aggregator REST API pending certificate route to broadcast the signed entity type currently signed
- [x] #892
- [x] #893
- [x] #894
- [x] #899
- [x] #898
- [x] #927

## Later
- [ ] Adapt the explorer to handle new aggregator `/certificates` route
- [ ] Decommission previous snapshot routes from the aggregator REST API

## Future
- Implement the interface for the `Cardano Stake Distribution` signed entity type
- Make the signer compute its own open messages
- Decommission the pending certificate route (and use the epoch settings route for the protocol parameters and signer registrations broadcast)
- Implement multiple certificates creation at the same time (with parallel runtimes and adaptation of the register signatures routes)

## Depends
Issue #779
