### ISSUE TITLE
Integrate Mithril with SPO tooling

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#905]
## Issue
We want to make usage of Mithril nodes as friction less as possible in order to have the highest adoption rate among the SPO community. In order to do so, we can integrate Mithril into the [`Guild Operators`](https://cardano-community.github.io/guild-operators/) SPO community tools.

⚠ This is a nice to have feature for the `mainnet` release, but it is not strictly required and thus can be deployed continuously.

## To do

- [ ] Implement Mithril Signer (and Mithril Relay) deployment into the install tools of Guild Operators (see #862)
- [ ] Implement Mithril Signer (and Mithril Relay) monitoring into the monitoring tools of Guild Operators (see #862)
- [ ] Implement Mithril Aggregator deployment into the install tools of Guild Operators
- [ ] Implement Mithril Aggregator) monitoring into the monitoring tools of Guild Operators
- [ ] TBD

**Comment by jpraynaud** [comment]
Already implemented by the Guild Operators 🚀
